// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'AlteKamerer';

  @override
  String get calendar => 'Calendar';

  @override
  String get settings => 'Settings';

  @override
  String get logOut => 'Log out';

  @override
  String get language => 'Language';

  @override
  String get languageDescription => 'Choose which language AlteKamerer uses.';

  @override
  String get systemDefault => 'System default';

  @override
  String get swedish => 'Swedish';

  @override
  String get english => 'English';

  @override
  String get akCommonClose => 'Close';

  @override
  String get akCommonPassword => 'Password';

  @override
  String get akCommonUserName => 'User name';

  @override
  String get akCommonComing => 'Coming';

  @override
  String get akCommonNotComing => 'Not coming';

  @override
  String get akCommonGatherInHole => 'Gather at hålan';

  @override
  String get akCommonGatherThere => 'Gather there';

  @override
  String get akCommonConcertStarts => 'Concert starts';

  @override
  String get akCommonAtRehersalPlace => 'At rehersal place';

  @override
  String get akCommonPlayDuration => 'Play duration';

  @override
  String get akCommonSignUpNotAllowed =>
      'You can not sign up to this gig anymore. For more info, contact the board members';

  @override
  String get akCountdownDays => 'Days';

  @override
  String get akCountdownHours => 'Hours';

  @override
  String get akCountdownMinutes => 'Minutes';

  @override
  String get akCountdownSeconds => 'Seconds';

  @override
  String get akInstrumentAltsax => 'Alto sax';

  @override
  String get akInstrumentBalett => 'Ballet';

  @override
  String get akInstrumentBanjo => 'Banjo';

  @override
  String get akInstrumentBarytonsax => 'Baritone sax';

  @override
  String get akInstrumentDragspel => 'Accordion';

  @override
  String get akInstrumentEuphonium => 'Euphonium';

  @override
  String get akInstrumentFlojt => 'Flute';

  @override
  String get akInstrumentHorn => 'Horn';

  @override
  String get akInstrumentKlarinett => 'Clarinet';

  @override
  String get akInstrumentOboe => 'Oboe';

  @override
  String get akInstrumentSlagverk => 'Drums';

  @override
  String get akInstrumentTenorsax => 'Tenor sax';

  @override
  String get akInstrumentTrombon => 'Trombone';

  @override
  String get akInstrumentTrumpet => 'Trumpet';

  @override
  String get akInstrumentTuba => 'Tuba';

  @override
  String get akLoginLogIn => 'Log in';

  @override
  String get akMailboxMessageSent => 'Message sent';

  @override
  String get akMailboxSubject => 'Subject';

  @override
  String get akMailboxMessage => 'Message';

  @override
  String get akMailboxSend => 'Send';

  @override
  String get akMemberlistSearchHere => 'Search here';

  @override
  String get akMemberlistSearchForInstruments => 'Search for instruments';

  @override
  String get akMemberlistAdressRegister => 'Address register';

  @override
  String get akMusicShowAlbums => 'Show albums';

  @override
  String get akMusicSearchSongs => 'Search songs';

  @override
  String get akMusicSearchHere => 'Search here';

  @override
  String get akMusicAlbumFromGpt => 'Album description generated by ChatGPT';

  @override
  String get akProfileFirstName => 'First name';

  @override
  String get akProfileLastName => 'Last name';

  @override
  String get akProfileProfileUpdated => 'Profile updated';

  @override
  String get akProfileUserName => 'User name';

  @override
  String get akProfileEmail => 'Email';

  @override
  String get akProfilePhoneNumber => 'Phone number';

  @override
  String get akProfileInstrument => 'Instrument';

  @override
  String get akProfileSelectInstrument => 'Select instrument';

  @override
  String get akProfileOtherInstruments => 'Other instruments';

  @override
  String get akProfileUpdateProfile => 'Update profile';

  @override
  String get akProfileChangePassword => 'Change password';

  @override
  String get akProfilePasswordUpdated => 'Password updated';

  @override
  String get akProfileNewPassword => 'New password';

  @override
  String get akProfileConfirmPassword => 'Confirm password';

  @override
  String get akProfileUpdatePassword => 'Update password';

  @override
  String get akProfileRoles => 'Roles';

  @override
  String get akProfilePosts => 'Posts';

  @override
  String get akProfileLatestMedal => 'Latest medal';

  @override
  String get akProfileLatestMedalGiven => 'Latest medal given';

  @override
  String get akProfileUserInfo => 'User info';

  @override
  String get akProfileStatisticsHeader => 'Statistics';

  @override
  String get akProfileStatisticsPreamble =>
      'Statistics for your performances the last year';

  @override
  String get akProfileHalan => 'Performances where you came via Hålan';

  @override
  String get akProfileDirect => 'Performances where you came directly';

  @override
  String get akProfileCantCome => 'Performances where you couldn\'t come';

  @override
  String get akProfileCar => 'Performances where you drove a car';

  @override
  String get akProfileInstrumentOwn =>
      'Performances where you brought your own instrument';

  @override
  String get akProfileComment => 'Performances where you left a comment';

  @override
  String get akProfileTotalGigs => 'Total number of performances';

  @override
  String get akProfileNoSignup =>
      'Performances you haven\'t signed up for/signed up absence to';

  @override
  String get akSignupShowInfo => 'Show information';

  @override
  String get akSignupEditSignups => 'Edit signups';

  @override
  String get akSignupNeedInstrumentTransport => 'Needs instrument transport';

  @override
  String get akSignupHasCar => 'Has car';

  @override
  String get akSignupComingTo => 'Coming to';

  @override
  String get akSignupHalan => 'Hålan';

  @override
  String get akSignupDirect => 'Direct';

  @override
  String get akSignupCantCome => 'Can\'t come';

  @override
  String get akSignupBringsInstrument =>
      'Pack my instrument, please. I will describe my case in the comment below (if no nametag is present).';

  @override
  String get akSignupComment => 'Comment';

  @override
  String get akSignupSignUp => 'Sign up';

  @override
  String get akSignupInstrument => 'Instrument';

  @override
  String get akSignupNoInstrument => 'No instrument';

  @override
  String get akUpcomingSignUp => 'Sign up';

  @override
  String get akUpcomingSignedUp => 'Signed up';

  @override
  String get akUpcomingAboutEvent => 'More info';

  @override
  String get akUpcomingTypeOfPlay => 'Type of concert';

  @override
  String get akUpcomingFikaAndClean => 'Fika and cleaning';

  @override
  String get akUpcomingIcalLink => 'iCal-link';

  @override
  String get akUpcomingList => 'List';

  @override
  String get akUpcomingMonth => 'Month';

  @override
  String get akUpcomingAllFilter => 'All rehearsals';

  @override
  String get akUpcomingBalletFilter => 'Ballet rehearsals';

  @override
  String get akUpcomingOrchestraFilter => 'Orchestra rehearsals';

  @override
  String get akUpcomingNoConcerts =>
      'Unfortunately we have no planned public concerts in the upcoming weeks';

  @override
  String get akUpcomingRep => 'Orchestra rehearsal';

  @override
  String get akUpcomingKarhusrep => 'Student union building rehearsal';

  @override
  String get akUpcomingBalettrep => 'Ballet rehearsal';

  @override
  String get akUpcomingAthenrep => 'Athen rehearsal';

  @override
  String get akUpcomingSamlingsrep => 'Collective rehearsal';

  @override
  String get akUpcomingFikarep => 'Fika rehearsal';

  @override
  String get akVideosSearchVideos => 'Search for video';

  @override
  String get akVideosShowAllVideos => 'Show all videos';

  @override
  String get akServiceCommonFirstName => 'First name';

  @override
  String get akServiceCommonLastName => 'Last name';

  @override
  String get akServiceCommonEmail => 'Email';

  @override
  String get akServiceCommonPhone => 'Telephone number';

  @override
  String get akServiceCommonSelectInstrument => 'Select instrument';

  @override
  String get akServiceCommonGigs => 'Upcoming gigs';

  @override
  String get akServiceCommonUpcoming => 'Upcoming';

  @override
  String get akServiceCommonContinueContent => 'Skip to content';

  @override
  String get akServiceWidgetsHireUs => 'Do you want to hire us?';

  @override
  String get akServiceWidgetsJoinUs => 'Do you want to play or dance with us?';

  @override
  String get akServiceWidgetsAnswerWithNumber => 'Answer with a number';

  @override
  String get akServiceWidgetsBotQuestion => 'What is 1 + 2?';

  @override
  String get akServiceWidgetsJoin => 'Join';

  @override
  String get akServiceWidgetsHire => 'Hire us';

  @override
  String get akServiceHeaderLogIn => 'Log in';

  @override
  String get akServiceHeaderLogOut => 'Log out';

  @override
  String get akServiceHeaderUnreadInterested => 'unread interested';

  @override
  String get akServiceHeaderLoggedInAs => 'Logged in as';

  @override
  String get akServiceErrorWrongPage =>
      'Hello, this is the wrong page you nitwit';

  @override
  String get akServiceErrorNothingToSee => 'Nothing to see here...';

  @override
  String get akServiceInstrumentAccordion => 'Accordion';

  @override
  String get akServiceInstrumentAltsax => 'Alto sax';

  @override
  String get akServiceInstrumentBalett => 'Ballet';

  @override
  String get akServiceInstrumentBanjo => 'Banjo';

  @override
  String get akServiceInstrumentBarytonsax => 'Baritone sax';

  @override
  String get akServiceInstrumentEuphonium => 'Euphonium';

  @override
  String get akServiceInstrumentFlute => 'Flute';

  @override
  String get akServiceInstrumentHorn => 'Horn';

  @override
  String get akServiceInstrumentKlarinett => 'Clarinet';

  @override
  String get akServiceInstrumentOboe => 'Oboe';

  @override
  String get akServiceInstrumentSlagverk => 'Drums';

  @override
  String get akServiceInstrumentTenorsax => 'Tenor sax';

  @override
  String get akServiceInstrumentTrombon => 'Trombone';

  @override
  String get akServiceInstrumentTrumpet => 'Trumpet';

  @override
  String get akServiceInstrumentTuba => 'Tuba';

  @override
  String get akServiceUpcomingPageTitle => 'Upcoming';

  @override
  String get akServiceUpcomingSignupPageTitle => 'Sign-up';

  @override
  String get akServiceUpcomingInvalidData => 'Invalid data';

  @override
  String get akServiceUpcomingInvalidId => 'Invalid id';

  @override
  String get akServiceUpcomingMustChooseWhere =>
      'You must choose whether you are coming via Hålan, direct, or not at all';

  @override
  String get akServiceUpcomingSignupUpdated => 'Sign-up updated';

  @override
  String get akServiceProfilePageTitle => 'Profile';

  @override
  String get akServiceProfileDuplicateInstrument =>
      'You cannot select the same instrument as both primary and additional instrument.';

  @override
  String get akServiceProfileProfileUpdated => 'Your profile was updated';

  @override
  String get akServiceProfilePasswordChanged => 'Password changed';

  @override
  String get akPostsOk => 'Chairman';

  @override
  String get akPostsKk => 'Treasurer';

  @override
  String get akPostsSk => 'Secretary';

  @override
  String get akPostsOpk => 'Vice Chairman';

  @override
  String get akPostsBallet => 'Responsible for the ballet';

  @override
  String get akPostsMusic => 'Responsible for the artistic - conductor';

  @override
  String get akPostsPub => 'Responsible for the pub';

  @override
  String get akPostsSex => 'Responsible for parties';

  @override
  String get akPostsArsenal =>
      'Responsible for orchestras instruments and the reparations for them';

  @override
  String get akPostsBus => 'Responsible for the pig (bus)';

  @override
  String get akPostsCamera =>
      'Responsible for documenting AK in photo and video';

  @override
  String get akPostsHug =>
      'Responsible for acting like a safe contact for the members of the organisation';

  @override
  String get akPostsCozy =>
      'Responsible for making Hålan cozy(toilet paper etc)';

  @override
  String get akPostsNintendo =>
      'Responsible for the computer in Hålan, AKs website, info and snack email lists';

  @override
  String get akPostsNostalgia =>
      'Responsible for the orchestras collective memory';

  @override
  String get akPostsNote => 'Responsible for note archive';

  @override
  String get akPostsPr =>
      'Responsible for us being heard and seen via for example posters';

  @override
  String get akPostsGadget => 'Responsible for medals, t-shirts, brands etc.';

  @override
  String get akPostsScrub =>
      'Responsible for Hålan, for exampel light bulbs etc.';

  @override
  String get akPostsSponsor => 'Responsible for finding sponsors';

  @override
  String get akPostsBitKamerer =>
      'Responsible for filming the ballet\'s new choreographies after each rehearsal and uploading them to the website';

  @override
  String get akPostsSyKamerer =>
      'Responsible for sewing the ballet\'s uniform skirts';

  @override
  String get akPostsBoard => 'Board';

  @override
  String get akPostsFunctionaries => 'Functionaries';

  @override
  String get akPostsOtherPosts => 'Other posts';

  @override
  String get retry => 'Try again';

  @override
  String get sessionCheckFailed =>
      'AlteKamerer could not verify your login with AKCore.';

  @override
  String get loginDescription => 'Log in with your existing AK account.';

  @override
  String get usernameRequired => 'Enter your user name.';

  @override
  String get passwordRequired => 'Enter your password.';

  @override
  String get loggingIn => 'Logging in…';

  @override
  String get invalidCredentials => 'Incorrect user name or password.';

  @override
  String get loginFailed => 'Could not log in. Try again.';

  @override
  String get akCoreConnectionFailed =>
      'Could not connect to AKCore. Try again.';

  @override
  String get calendarLoadFailed => 'Could not load the calendar';

  @override
  String get calendarLoadFailedMessage =>
      'AlteKamerer could not load upcoming activities from AKCore.';

  @override
  String get calendarDate => 'Date';

  @override
  String get calendarTime => 'Time';

  @override
  String get calendarType => 'Type';

  @override
  String get calendarPlace => 'Place';

  @override
  String get noUpcomingActivities => 'No upcoming activities';

  @override
  String get emptyCalendar =>
      'There are no activities in the calendar right now.';

  @override
  String get registeredAttending => 'Signed up and attending';

  @override
  String get registeredNotAttending => 'Signed up but not attending';

  @override
  String get notRegistered => 'Not signed up';

  @override
  String get connectionFailed => 'Could not connect';

  @override
  String get activity => 'Activity';

  @override
  String get eventLoadFailed => 'Could not load activity';

  @override
  String get eventLoadFailedMessage =>
      'AlteKamerer could not load the activity from AKCore.';

  @override
  String get eventDisplayFailed => 'Could not display activity';

  @override
  String get eventInfoMissing => 'Activity information is missing.';

  @override
  String get eventOnSite => 'On site';

  @override
  String get eventStart => 'Start';

  @override
  String get eventPlayDuration => 'Play time';

  @override
  String get eventMusicStand => 'Music stand';

  @override
  String get information => 'Information';

  @override
  String get internalInformation => 'Internal information';

  @override
  String get eventRegistration => 'Registration';

  @override
  String yourStatus(String status) {
    return 'Your status: $status';
  }

  @override
  String registrationCounts(int coming, int notComing) {
    return '$coming attending · $notComing not attending';
  }

  @override
  String get registrationClosed => 'Registration is closed for this activity.';

  @override
  String get registrationUnavailable =>
      'Registration can no longer be changed for this activity.';

  @override
  String get changeRegistration => 'Change registration';

  @override
  String get signUp => 'Sign up';

  @override
  String get hasCar => 'Has car';

  @override
  String get bringsOwnInstrument => 'Bringing own instrument';

  @override
  String get saveRegistration => 'Save registration';

  @override
  String get selectArrivalRequired => 'You must choose how you are arriving.';

  @override
  String get registrationSaveInvalid =>
      'Registration could not be saved. Check the information and try again.';

  @override
  String get activityNoLongerExists => 'The activity no longer exists.';

  @override
  String get registrationSaveFailed =>
      'Registration could not be saved. Try again.';

  @override
  String get reminders => 'Reminders';

  @override
  String get remindersDescription =>
      'Choose how long before an activity you want to be reminded.';

  @override
  String get noRemindersEnabled => 'No reminders are enabled.';

  @override
  String get addReminder => 'Add reminder';

  @override
  String get saveSettings => 'Save settings';

  @override
  String get reminderTimeBefore => 'Time before';

  @override
  String get unit => 'Unit';

  @override
  String get removeReminder => 'Remove reminder';

  @override
  String get reminderPositiveTimeRequired =>
      'All reminders must have a time greater than 0.';

  @override
  String get duplicateReminderTime =>
      'Two reminders cannot have the same time before the activity.';

  @override
  String get remindersSaved => 'Reminders saved.';

  @override
  String get remindersSaveFailed =>
      'The reminders could not be saved. Try again.';

  @override
  String get settingsLoadFailed => 'Could not load settings';

  @override
  String get reminderSettingsLoadFailed =>
      'The reminder settings could not be loaded.';

  @override
  String get notificationChannelName => 'Activity reminders';

  @override
  String get notificationChannelDescription =>
      'Reminders for activities in AlteKamerer';

  @override
  String get notificationStartsInOneHour => 'Starts in 1 hour';

  @override
  String notificationStartsInHours(int hours) {
    return 'Starts in $hours hours';
  }

  @override
  String notificationStartsInMinutes(int minutes) {
    return 'Starts in $minutes minutes';
  }
}
